import sys 
sys.path.insert(1, '/mnt/gunkaynar/refactor_dataset/cpmg/lib/pyNMR')
import nmrDataMod as ndm
import numpy as np
# process free induction decay(fid) data and create a spectrum similar to Topspin's output
def preprocess_spectrum(path):
    data = ndm.nmrData(path, "TopSpin")
    shiftPoints = 70  # first 70 points are not actual data.
    data.leftShift(0, 1, shiftPoints)
    data.lineBroadening(1,2,20)
    data.fourierTransform(1,2)
    phase = data.autoPhase0(2,0,-50000,50000)
    data.phase(2,3, phase)
    return (np.absolute(data.allFid[3][0])).T

control_spectrum = []
labels = []
shift_ = -1515
for i in range(1,17):
    n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/control/N" + str(i) + "/"))
    control_spectrum.append(np.roll(n,shift_))
    labels.append(0)

tumor_spectrum = []
benign_aggressive = []
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/AA1/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/DA1/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(0)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/DA5/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(0)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/DA6/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(0)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/DA7/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(0)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM2/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM3/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM5/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM6/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM7/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM8/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM9/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM10/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM17_2/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM19/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM20/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM23/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM25/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM27/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM28/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/GBM29/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/PA1/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(0)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/PA2/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(0)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/PA3/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(0)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/PA4/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(0)
n = (preprocess_spectrum("/mnt/gunkaynar/data/test_data_FID/tumor/QDA9/"))
tumor_spectrum.append(np.roll(n,shift_))
labels.append(1)
benign_aggressive.append(1)

labels = np.reshape(labels,(1,42))



spectrums = np.append((control_spectrum),(tumor_spectrum),axis=0)

normalization_ = 1.6
spectra_test = spectrums/normalization_
labels_test = labels
tumor_spectrum_test = np.divide(tumor_spectrum,normalization_)
benign_aggressive_test = benign_aggressive

